ClusterName=labcluster
SlurmUser=slurm
SlurmctldHost=lab-admin
AuthType=auth/munge

#Storage
StateSaveLocation=/var/lib/slurm/slurmctld
SlurmctldLogFile=/var/log/slurmctld.log
SlurmdLogFile=/var/log/slurmd.log

#Accounting Storage
AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageHost=lab-admin
AccountingStorageEnforce=associations
AccountingStoragePort=6819

NodeName=lab-compute CPUs=2 RealMemory=1900 State=IDLE
PartitionName=debug Nodes=lab-compute Default=YES MaxTime=00:05:00 State=UP
