- name: Day 6 Part 4 - Using Real Modules
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Ensure common packages are installed
      apt: 
        name: 
          - vim
          - curl
          - wget
          - git
        state: present
    
    - name: Ensure researcher group exists
      group:
        name: researchers
        state: present
    
    - name: Ensure /research directory exists with correct permisions
      file:
        path: /research
        state: directory
        owner: root
        group: researchers
        mode: "2775"
    
    - name: Ensure SSH servce is running and enabled
      service: 
        name: ssh 
        state: started
        enabled: true
  

